// examples/solid/src/lib/use-flex-search.ts
import FlexSearch, { type Index as FlexSearchIndex } from "flexsearch"
import { createEffect, createMemo, createSignal, on } from "solid-js"

/**
 * Reactive FlexSearch index over a Solid accessor of items. Rebuilds the
 * index whenever `data()` changes. Returns a `search(query)` accessor that
 * yields the matched items in index order; an empty/whitespace query yields
 * all items (when `returnAllOnEmpty` is true, the default).
 */
export function createFlexSearchIndex<T>(
  data: () => T[],
  options: {
    indexerFn: (item: T) => string
    returnAllOnEmpty?: boolean
  }
) {
  const returnAllOnEmpty = options.returnAllOnEmpty ?? true
  const [index, setIndex] = createSignal<FlexSearchIndex | null>(null)

  createEffect(
    on(data, (items) => {
      const idx = new FlexSearch.Index({ tokenize: "full" })
      items.forEach((item, i) => {
        idx.add(i, options.indexerFn(item))
      })
      setIndex(idx)
    })
  )

  function search(query: string): T[] {
    const items = data()
    const q = query.trim()
    if (!q) return returnAllOnEmpty ? items : []
    const idx = index()
    if (!idx) return returnAllOnEmpty ? items : []
    const results = idx.search(q, { limit: items.length })
    const out: T[] = []
    for (const i of results) out.push(items[i as number])
    return out
  }

  return { search }
}

/** Convenience: a memo'd search result for a reactive query. */
export function createFlexSearch<T>(
  data: () => T[],
  query: () => string,
  options: { indexerFn: (item: T) => string; returnAllOnEmpty?: boolean }
) {
  const { search } = createFlexSearchIndex(data, options)
  return createMemo(() => search(query()))
}

// examples/react/src/lib/use-flex-search.ts
import FlexSearch, { type Index as FlexSearchIndex } from "flexsearch"
import { useCallback, useEffect, useMemo, useState } from "react"

/**
 * Reactive FlexSearch index over an array of items. Rebuilds the index whenever
 * `data` changes. Returns a `search(query)` function that yields matched items
 * in index order; an empty/whitespace query yields all items when
 * `returnAllOnEmpty` is true, the default.
 */
export function useFlexSearchIndex<T>(
  data: T[],
  options: {
    indexerFn: (item: T) => string
    returnAllOnEmpty?: boolean
  },
) {
  const returnAllOnEmpty = options.returnAllOnEmpty ?? true
  const [index, setIndex] = useState<FlexSearchIndex | null>(null)

  useEffect(() => {
    const idx = new FlexSearch.Index({ tokenize: "full" })
    data.forEach((item, i) => {
      idx.add(i, options.indexerFn(item))
    })
    setIndex(idx)
  }, [data, options.indexerFn])

  const search = useCallback(
    (query: string): T[] => {
      const q = query.trim()
      if (!q) return returnAllOnEmpty ? data : []
      if (!index) return returnAllOnEmpty ? data : []

      const results = index.search(q, { limit: data.length })
      const out: T[] = []
      for (const i of results) {
        const item = data[i as number]
        if (item !== undefined) out.push(item)
      }
      return out
    },
    [data, index, returnAllOnEmpty],
  )

  return { search }
}

/** Convenience: a memo'd search result for a reactive query. */
export function useFlexSearch<T>(
  data: T[],
  query: string,
  options: { indexerFn: (item: T) => string; returnAllOnEmpty?: boolean },
) {
  const { search } = useFlexSearchIndex(data, options)
  return useMemo(() => search(query), [query, search])
}
