// examples/react/src/lib/model-catalog/use-provider-configs.ts
import { useMemo } from "react"
import type { Catalog } from "model-catalog"
import type { ProviderConfig } from "./types"

/**
 * Derives provider configuration state for the demo app.
 *
 * In a real app, `sourceProviderConfigs` can come from your backend instead of
 * local demo state, e.g. `const { data } = useQuery(api.providerConfigs.list)`.
 * The backend should return safe metadata such as `{ providerId, isConfigured,
 * isEnabled }`, not raw API keys or other secrets.
 */
export function useProviderConfigs(
  catalog: Catalog,
  configuredProviderIds: readonly string[],
  providerSearch: string,
  sourceProviderConfigs?: ProviderConfig[],
) {
  const providers = useMemo(() => catalog.listProviders(), [catalog])
  const visibleProviders = useMemo(() => catalog.listProviders({ query: providerSearch }), [catalog, providerSearch])
  const configuredProviders = useMemo(() => new Set(configuredProviderIds), [configuredProviderIds])

  const providerConfigs = useMemo<ProviderConfig[]>(
    () =>
      sourceProviderConfigs ??
      providers.map((provider) => ({
        id: provider.id,
        provider: provider.id,
        providerId: provider.id,
        isConfigured: configuredProviders.has(provider.id),
        isEnabled: true,
      })),
    [configuredProviders, providers, sourceProviderConfigs],
  )
  const enabledProviders = useMemo(
    () => providerConfigs.filter((provider) => provider.isEnabled && provider.isConfigured).map((provider) => provider.providerId),
    [providerConfigs],
  )
  const enabledCount = enabledProviders.length

  return { providers, visibleProviders, providerConfigs, enabledProviders, enabledCount }
}

// examples/solid/src/lib/model-catalog/use-provider-configs.ts
import { createMemo, type Accessor } from "solid-js"
import type { Catalog } from "model-catalog"
import type { ProviderConfig } from "./types"

/**
 * Derives provider configuration state for the demo app.
 *
 * In a real app, `sourceProviderConfigs` can come from your backend instead of
 * local demo state, e.g. `const providerConfigsQuery = createResource(...)`.
 * The backend should return safe metadata such as `{ providerId, isConfigured,
 * isEnabled }`, not raw API keys or other secrets.
 */
export function useProviderConfigs(
  catalog: Accessor<Catalog>,
  configuredProviderIds: Accessor<readonly string[]>,
  providerSearch: Accessor<string>,
  sourceProviderConfigs?: Accessor<ProviderConfig[] | undefined>,
) {
  const providers = createMemo(() => catalog().listProviders())
  const visibleProviders = createMemo(() => catalog().listProviders({ query: providerSearch() }))
  const providerConfigs = createMemo<ProviderConfig[]>(
    (previous) => {
      const source = sourceProviderConfigs?.()
      if (source) return source

      const configuredProviders = new Set(configuredProviderIds())
      const next = providers().map((provider, index) => {
        const isConfigured = configuredProviders.has(provider.id)
        const current = previous?.[index]
        if (current?.id === provider.id && current.isConfigured === isConfigured) return current

        return {
          id: provider.id,
          provider: provider.id,
          providerId: provider.id,
          isConfigured,
          isEnabled: true,
        }
      })

      if (previous && previous.length === next.length && next.every((provider, index) => provider === previous[index])) return previous
      return next
    },
    [],
  )
  const enabledProviders = createMemo(() =>
    providerConfigs()
      .filter((provider) => provider.isEnabled && provider.isConfigured)
      .map((provider) => provider.providerId),
  )
  const enabledCount = () => enabledProviders().length

  return { providers, visibleProviders, providerConfigs, enabledProviders, enabledCount }
}
