// examples/react/src/lib/model-catalog/use-selected-chat-model.ts
import { useEffect, useMemo, useState } from "react"
import type { Catalog } from "model-catalog"
import type { ChatModelValue } from "./types"

export function useSelectedChatModel(catalog: Catalog, enabledProviders: string[]) {
  const availableModels = useMemo(
    () =>
      catalog.listModels({
        includeProviders: enabledProviders,
        outputModalities: ["text"],
        excludeDeprecated: true,
        groupBy: "providerId",
      }),
    [catalog, enabledProviders],
  )
  const firstAvailable = availableModels.groups[0]?.models[0]
  const firstAvailableValue = firstAvailable ? { provider: firstAvailable.providerId, modelId: firstAvailable.modelId } : null
  const [selectedModel, setSelectedModel] = useState<ChatModelValue | null>(firstAvailableValue)

  useEffect(() => {
    if (!selectedModel && firstAvailableValue) {
      setSelectedModel(firstAvailableValue)
      return
    }
    if (!selectedModel || enabledProviders.includes(selectedModel.provider)) return
    setSelectedModel(firstAvailableValue)
  }, [enabledProviders, firstAvailableValue, selectedModel])

  return { selectedModel, setSelectedModel }
}

// examples/solid/src/lib/model-catalog/use-selected-chat-model.ts
import { createEffect, createMemo, createSignal, type Accessor } from "solid-js"
import type { Catalog } from "model-catalog"
import type { ChatModelValue } from "./types"

export function useSelectedChatModel(catalog: Accessor<Catalog>, enabledProviders: Accessor<string[]>) {
  const availableModels = createMemo(() =>
    catalog().listModels({
      includeProviders: enabledProviders(),
      outputModalities: ["text"],
      excludeDeprecated: true,
      groupBy: "providerId",
    }),
  )
  const firstAvailable = createMemo<ChatModelValue | null>(() => {
    const first = availableModels().groups[0]?.models[0]
    return first ? { provider: first.providerId, modelId: first.modelId } : null
  })
  const [selectedModel, setSelectedModel] = createSignal<ChatModelValue | null>(firstAvailable())
  const selectedProvider = createMemo(() => selectedModel()?.provider ?? null)

  createEffect(() => {
    const provider = selectedProvider()
    if (!provider) {
      const fallback = firstAvailable()
      if (!fallback) return
      setSelectedModel(fallback)
      return
    }
    if (!enabledProviders().includes(provider)) setSelectedModel(firstAvailable())
  })

  return { selectedModel, setSelectedModel }
}
